/**
 * Scaffolding hints route + engine integration (mocked Neo4j driver).
 *
 * - Captures the Cypher generated by scaffoldingPlan to assert it reads
 *   :ObjectiveState.bloomsMaxReached and :LearningObjective.blooms_index
 *   scoped to the chemie subset.
 * - Asserts GET /api/scaffolding/hints returns the plan / 404 / 401 / 400.
 */

import { vi, describe, test, expect, beforeEach } from 'vitest';
import express from 'express';

let captured = null;
let runImpl = null;

vi.mock(
  'neo4j-driver',
  () => ({
    default: { session: { READ: 'READ' } },
  })
);

vi.mock(
  '../api/services/neo4j.js',
  () => ({
    getNeo4jDriver: () => ({
      session: () => ({
        run: async (query, params) => {
          captured = { query, params };
          if (runImpl) return runImpl(query, params);
          return { records: [] };
        },
        close: async () => {},
      }),
    }),
    NEO4J_DATABASE: 'chemie',
    toNumberSafe: (v) => (v == null ? undefined : Number(v)),
  })
);

vi.mock(
  '../scripts/_neo4j-subset-filter.mjs',
  () => ({
    subsetMatch: () => 'WHERE (lo:LearningObjective)',
  })
);

vi.mock(
  '../api/auth.js',
  () => ({
    requireAuth: vi.fn((req, res, next) => {
      if (!req.user?.id) return res.status(401).json({ error: 'Authentication required' });
      next();
    }),
  })
);

const { default: router } = await import('../api/routes/scaffolding.js');

function createTestServer(authUser = null) {
  const app = express();
  app.disable('x-powered-by');
  app.use(express.json());
  app.use((req, res, next) => {
    req.user = authUser;
    next();
  });
  app.use(router);
  return app.listen(0);
}

function makeRecord(map) {
  return {
    get: (key) => map[key],
  };
}

describe('scaffoldingPlan Cypher', () => {
  beforeEach(() => {
    captured = null;
    runImpl = null;
  });

  test('queries ObjectiveState.bloomsMaxReached + LearningObjective.blooms_index scoped to subset', async () => {
    runImpl = async (query) => {
      expect(query).toContain('(lo:LearningObjective {slug: $objectiveSlug})');
      expect(query).toContain('AND lo.blooms_index IS NOT NULL');
      expect(query).toContain('(s:ObjectiveState)-[:FOR]->(lo)');
      expect(query).toContain('coalesce(s.bloomsMaxReached, 0) AS learnerBloom');
      expect(query).toContain('lo.blooms_index AS targetBloom');
      // subset scoping is present
      expect(query).toContain('WHERE (lo:LearningObjective)');
      return { records: [makeRecord({ targetBloom: 4, learnerBloom: 2 })] };
    };
    const { scaffoldingPlan } = await import('../api/services/scaffolding-engine.js');
    const plan = await scaffoldingPlan('u1', 'stoffe-teilchen-lo-3');
    expect(plan.objectiveSlug).toBe('stoffe-teilchen-lo-3');
    expect(plan.targetBloom).toBe(4);
    expect(plan.learnerBloom).toBe(2);
    expect(plan.gap).toBe(2);
    expect(plan.totalSteps).toBe(2);
    expect(captured.params).toEqual({ objectiveSlug: 'stoffe-teilchen-lo-3', userId: 'u1' });
  });

  test('cold-start (no ObjectiveState) defaults learnerBloom to 0', async () => {
    runImpl = async () => ({ records: [makeRecord({ targetBloom: 3, learnerBloom: 0 })] });
    const { scaffoldingPlan } = await import('../api/services/scaffolding-engine.js');
    const plan = await scaffoldingPlan('u2', 'lo-x');
    expect(plan.learnerBloom).toBe(0);
    expect(plan.totalSteps).toBe(3);
  });

  test('missing objective returns null', async () => {
    runImpl = async () => ({ records: [] });
    const { scaffoldingPlan } = await import('../api/services/scaffolding-engine.js');
    const plan = await scaffoldingPlan('u3', 'ghost');
    expect(plan).toBeNull();
  });
});

describe('GET /api/scaffolding/hints', () => {
  beforeEach(() => {
    captured = null;
    runImpl = null;
  });

  test('401 when unauthenticated', async () => {
    const server = createTestServer(null);
    try {
      const res = await fetch(`http://127.0.0.1:${server.address().port}/api/scaffolding/hints?objectiveSlug=x`);
      expect(res.status).toBe(401);
    } finally {
      server.close();
    }
  });

  test('400 when objectiveSlug missing', async () => {
    const server = createTestServer({ id: 'u1' });
    try {
      const res = await fetch(`http://127.0.0.1:${server.address().port}/api/scaffolding/hints`);
      expect(res.status).toBe(400);
    } finally {
      server.close();
    }
  });

  test('404 when objective not found', async () => {
    runImpl = async () => ({ records: [] });
    const server = createTestServer({ id: 'u1' });
    try {
      const res = await fetch(`http://127.0.0.1:${server.address().port}/api/scaffolding/hints?objectiveSlug=ghost`);
      expect(res.status).toBe(404);
    } finally {
      server.close();
    }
  });

  test('200 with plausible plan for authenticated user', async () => {
    runImpl = async () => ({ records: [makeRecord({ targetBloom: 4, learnerBloom: 2 })] });
    const server = createTestServer({ id: 'u1' });
    try {
      const res = await fetch(`http://127.0.0.1:${server.address().port}/api/scaffolding/hints?objectiveSlug=stoffe-teilchen-lo-3`);
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body.objectiveSlug).toBe('stoffe-teilchen-lo-3');
      expect(body.gap).toBe(2);
      expect(body.totalSteps).toBe(2);
      expect(body.staircase[0].hintType).toBe('worked-example');
      expect(body.staircase[1].hintType).toBe('socratic-question');
    } finally {
      server.close();
    }
  });
});