#!/usr/bin/env python3
"""
static-server.py — minimal static file server for the Hubs client dist/.

Replaces the webpack-dev-server in production. Serves /code/dist with the same
historyApiFallback rewrites Hubs' dev server used to apply:
  /link        -> /link.html
  /avatars     -> /avatar.html
  /scenes      -> /scene.html
  /signin      -> /signin.html
  /discord     -> /discord.html
  /cloud       -> /cloud.html
  /verify      -> /verify.html
  /tokens      -> /tokens.html
  /<7-char>    -> /hub.html        (room slugs)
Everything else without a file extension falls back to /index.html (SPA).
"""
import http.server
import socketserver
import os
import re
import sys
import json
import ssl
from urllib.parse import unquote
from urllib.request import urlopen

DIST = os.environ.get("HUBS_DIST", "/code/dist")

# Legacy room URL format: /hub/<7-char-id>[/<slug>]. Generated by a
# chemie-portal.js bug (built links with a /hub/ prefix, fixed 2026-09-02).
# Links in that format may still live in bookmarks/chat logs/search indexes.
# We 301-redirect to the canonical /<id>[/<slug>] instead of rewriting:
# serving hub.html AT this path would make the client parse "hub" as the
# room ID (getCurrentHubId() takes the first path segment).
HUB_LEGACY_RE = re.compile(r"^/hub/([A-Za-z0-9]{7})(?:/([A-Za-z0-9_-]*))?/?$")

REWRITES = [
    (r"^/link", "/link.html"),
    (r"^/avatars", "/avatar.html"),
    (r"^/scenes", "/scene.html"),
    (r"^/signin", "/signin.html"),
    (r"^/discord", "/discord.html"),
    (r"^/cloud", "/cloud.html"),
    (r"^/verify", "/verify.html"),
    (r"^/tokens", "/tokens.html"),
# Match 7-char hub IDs with optional slug (e.g. /raJ6mj3 or
# /raJ6mj3/test-room).  The slug is restricted to [A-Za-z0-9_-] so that
# file paths like /<hubId>/objects.gltf or /<hubId>/scene.glb do NOT
# match and instead get a clean 404 (serving hub.html for a .gltf
# request causes a SyntaxError when the glTF loader tries to parse
# HTML as JSON).  An optional trailing slash is allowed so that
# /raJ6mj3/test-room/ also serves hub.html (not index.html).
#
# NOTE: matching happens on the PERCENT-DECODED path (see
# _resolve_target) and slugs accept any character except '/', '.' and
# '?': recovered legion rooms have unicode slugs like
# /JQLHx3e/chemie-raum-–-wasserstoff-h (en-dash from the German
# element-room names).  Dot-paths still never match (they contain '.').
    (r"^/[A-Za-z0-9]{7}(?:/[^./?]*|/)?$", "/hub.html"),
]

# Reticulum per-room content that must NOT be 404'd by the dot-path rule:
# the client fetches /<hubId>/objects.gltf (pinned room objects / spawn
# points) on every room load.  A 404 here makes the client log "Releasing
# uncached gltf #spawn-point" and can break the entry flow (black room).
# We proxy to reticulum (same docker network) and fall back to an empty
# spec-valid glTF if reticulum is unreachable.
ROOM_OBJECTS_RE = re.compile(r"^/[A-Za-z0-9]{7}/objects\.gltf$")
RETICULUM_ORIGIN = os.environ.get("RETICULUM_ORIGIN", "https://hubs-reticulum:4000")
# reticulum's internal endpoint uses a self-signed cert — skip verification
_SSL_CTX = ssl.create_default_context()
_SSL_CTX.check_hostname = False
_SSL_CTX.verify_mode = ssl.CERT_NONE
EMPTY_GLTF = json.dumps(
    {
        "asset": {"version": "2.0", "generator": "hubs-client-assets static server"},
        "scene": 0,
        "scenes": [{"name": "scene", "nodes": []}],
        "nodes": [],
    }
).encode("utf-8")

class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIST, **kwargs)

    def guess_type(self, path):
        # Force correct MIME types (SimpleHTTPRequestHandler's mimetypes DB is
        # often missing these, which makes browsers reject the PWA manifest
        # and ES modules).
        if path.endswith(".webmanifest"):
            return "application/manifest+json"
        if path.endswith(".js"):
            return "application/javascript"
        if path.endswith(".json"):
            return "application/json"
        return super().guess_type(path)

    def _resolve_target(self):
        """Resolve self.path to the file to serve, applying REWRITES and SPA
        fallback.  Returns the target path, or None for 404."""
        path = unquote(self.path.split("?")[0].split("#")[0])
        target = path
        for pat, rep in REWRITES:
            if re.match(pat, path):
                target = rep
                break
        fs_path = os.path.join(DIST, target.lstrip("/"))
        if os.path.isfile(fs_path):
            return target
        # SPA fallback only for extensionless routes.
        if "." not in os.path.basename(path):
            return "/index.html"
        return None

    def _legacy_redirect_target(self):
        """Return the canonical redirect target for legacy /hub/<id>/<slug>
        URLs, or None if self.path is not a legacy room URL."""
        path, sep, query = self.path.partition("?")
        m = HUB_LEGACY_RE.match(path)
        if not m:
            return None
        hub_id, slug = m.group(1), m.group(2)
        target = f"/{hub_id}/{slug}" if slug else f"/{hub_id}"
        if query:
            target += "?" + query
        return target

    def _serve_room_objects(self):
        """Proxy /<hubId>/objects.gltf to reticulum; fall back to an empty
        spec-valid glTF if reticulum is unreachable. Returns True if handled."""
        if not ROOM_OBJECTS_RE.match(self.path.split("?")[0]):
            return False
        self.send_response(200)
        self.send_header("Content-Type", "model/gltf+json; charset=utf-8")
        try:
            upstream = urlopen(RETICULUM_ORIGIN + self.path, timeout=5, context=_SSL_CTX)
            body = upstream.read()
            length = len(body)
        except Exception:
            body, length = EMPTY_GLTF, len(EMPTY_GLTF)
        self.send_header("Content-Length", str(length))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)
        return True

    def do_GET(self):
        if self._serve_room_objects():
            return
        redirect = self._legacy_redirect_target()
        if redirect is not None:
            self.send_response(301)
            self.send_header("Location", redirect)
            self.end_headers()
            return
        target = self._resolve_target()
        if target is None:
            self.send_error(404, "Not Found: " + self.path)
            return
        self.path = target
        return super().do_GET()

    def do_HEAD(self):
        # Mirror do_GET routing so HEAD requests to room URLs (e.g. from
        # phoenix-adapter.js pre-flight checks) return 200, not 404.
        if self._serve_room_objects():
            return
        redirect = self._legacy_redirect_target()
        if redirect is not None:
            self.send_response(301)
            self.send_header("Location", redirect)
            self.end_headers()
            return
        target = self._resolve_target()
        if target is None:
            self.send_error(404, "Not Found: " + self.path)
            return
        self.path = target
        return super().do_HEAD()

    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-cache")
        super().end_headers()

    def log_message(self, *args):
        pass


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8080"))
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("0.0.0.0", port), Handler) as httpd:
        print(f"hubs static server on :{port} -> {DIST}", flush=True)
        httpd.serve_forever()
